version: '3'
services:
  nginx:
    image: nginx:1.15.6
    ports:
      - "8081:8081"
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    build: ./docker/php
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: practice_app
      MYSQL_USER: globalituser
      MYSQL_PASSWORD: GlobalIT@123
      MYSQL_ROOT_PASSWORD: GlobalIT@123
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: